name: Package Build

on:
  push:
    branches:
      - master
  schedule:
    - cron: "7 9,14,20 * * *"

jobs:
  bump-version:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
      with:
        # I setup a new token for my GitHub user and added that token
        # to the secrets in the repository
        # When I tried
        # https://docs.github.com/en/actions/reference/authentication-in-a-workflow
        # I had some problems, they could be my fault, but yet, I felt using a
        # dedicated token would be better and suffice
        token: ${{ secrets.PAT }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Setup Git
      run: |
        git config user.name "Benedict-Carling"
        git config user.email 'Benedict-Carling@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/Benedict-Carling/spanish-conjugator
        git checkout master
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bump2version setuptools wheel twine
    - name: Bump Patch Version
      env:
        COMMIT_MSG: ${{ github.event.head_commit.message }}
      run: |
        bump2version --current-version $(python setup.py --version ) patch setup.py

    - name: Commit version change to master - Push
      run: |
        git commit -am "[skip ci]Automated version bump"
        git push
      if: github.event_name == 'push'
    - name: Commit version change to master - Cron
      run: |
        git commit -am "Automated version bump"
        git push
      if: github.event_name == 'schedule'
    - name: Build and publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_UPLOAD_TOKEN }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*
